### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by zh-wowtv** [wix/react-native-keyboard-aware-scrollview#1]
When keyboard appears, the scrollview doesn't scroll at all.

**Comment by artald** [comment]
Can you share a gist with code that causes this issue? I can't reproduce it and we have several projects working with this component without any problem.

Also, have you tried the [example project](https://github.com/wix/react-native-keyboard-aware-scrollview/tree/master/example)? If this doesn't work for you maybe there's something else going on.
