### ISSUE TITLE
The prop "scrollToInputAdditionalOffset" is not documented

### ISSUE THREAD

**Issue by parijatsahai** [wix/react-native-keyboard-aware-scrollview#21]
Is there a reason why the prop "scrollToInputAdditionalOffset" is not documented?

**Comment by artald** [comment]
Hi @parijatsahai,

Assuming that you're asking regarding the readme, there's no particular reason why this wasn't documented. The readme wasn't properly maintained, other props are not documented there either... I agree that it can be improved.

That said, you can see the available props in the `propTypes`.
