### ISSUE TITLE
Repository outdated?

### ISSUE THREAD

**Issue by Strayer** [wix/react-native-keyboard-aware-scrollview#27]
[npm already has version 1.1.7](https://www.npmjs.com/package/react-native-keyboard-aware-scrollview), this repository has no mention of that version anywhere (no tags, no commits)

**Comment by dantman** [comment]
The library also appears to be unmaintained. There hasn't been any response to issues or PRs in a month.

**Comment by kashishgrover** [comment]
There seem to be a heck load of bugs on Android. I will probably have to kill my use. :(
