### ISSUE TITLE
keyboard scrollview created extra white space at bottom on android

### ISSUE THREAD

**Issue by SunilPandey-** [wix/react-native-keyboard-aware-scrollview#42]
Hi,

I am using ModalWrapper and inside there is another view. on ios it works fine. for android when keyboard opens i am unable to textinput content.

I tried to use react-native-keyboard-aware-scroll-view inside modalWrapper, but with it, topmost text input is getting hidden and there is extra white space at bottom of screen

**Comment by fabiodamasceno** [comment]
Can you post your react-native version, JSX and styles, please?

**Comment by SunilPandey-** [comment]
Issue resolved as of now for android. needed to give parent as flex 1,
